package migrations

import (
	"time"
	"database/sql"
	"context"

	"github.com/krixano/ponixserver/src/db"
	"github.com/krixano/ponixserver/src/migration/types"
)

func init() {
	registerMigration(Initial{})
}

type Initial struct{}

func (m Initial) Version() types.MigrationVersion {
	return types.MigrationVersion(time.Date(2021, 5, 20, 17, 9, 28, 0, time.UTC))
}

func (m Initial) Name() string {
	return "Initial"
}

func (m Initial) DB() db.DBType {
	return db.MusicDB
}

func (m Initial) Description() string {
	return "Initial Migration"
}

func (m Initial) Up(tx *sql.Tx) error {
	_, err := tx.ExecContext(context.Background(), `
	CREATE TABLE members (
		id integer generated by default as identity primary key,
		certificate character varying(2000) NOT NULL,
		username character varying(150) NOT NULL,
		language character varying(10) NOT NULL,
		timezone character varying(255) NOT NULL,
		is_staff boolean NOT NULL,
		is_active boolean NOT NULL,
		date_joined timestamp NOT NULL
	);
	`)
	if err != nil {
		return err
	}

	return nil
}

func (m Initial) Down(tx *sql.Tx) error {
	panic("Cannot do so. This is the initial migration.")
}
